### ISSUE TITLE
Android Client Nudge and Done Notifications

### ISSUE THREAD

**Issue by bawolf** [bawolf/choreapp#33]
Create a notification framework and receive notifications when:

User A receives a notification when they have nagged a task in the past and User B has completed that task.

User A receives a notification when user B has nudged a task that they are assigned.

receive GCM JSON payloads like below
```
{
format: task,
type: nag,
task_id: 1
}
```

**Comment by russhwolf** [comment]
Most of the framework is now in place (as of a forthcoming commit), but waiting on some server updates to be live in order to finish this out.
