### ISSUE TITLE
Android Client: Create Confirmation dialog for important actions

### ISSUE THREAD

**Issue by bawolf** [bawolf/choreapp#39]
some actions are too easy by accident and snack bars probably aren't appropriate
Accept Invitation - warn that it will remove you from your current place
Reject invitation - Are you sure?
Leave place - Are you sure?
Remove Roommate - Are you sure?
Remove Chore - Are you sure?

**Comment by russhwolf** [comment]
Addressed in [80779b7](https://github.com/bawolf/choreapp/commit/80779b709e7087407e4ec3cf1e8141f4c0378be2)
