### ISSUE TITLE
Add pictures of users

### ISSUE THREAD

**Issue by bawolf** [bawolf/choreapp#43]
In the Roommates screen users should see whatever photos they have attached to their roommates accounts in their contacts

**Comment by russhwolf** [comment]
Addressed in [f8e4001](https://github.com/bawolf/choreapp/commit/f8e400110532f51539de934bb9fb1d55892d4ab0)

We use the first non-null image we find associated with the email. A future version of this functionality might want to maintain separate ChoreApp account contacts which could be assigned custom images through the platform contacts functionality, but this might be overkill.
