### ISSUE TITLE
change password api call

### ISSUE THREAD

**Issue by russhwolf** [bawolf/choreapp#94]
For the sake of completion, it'd be nice to have a change password option on the settings screen.

Android implementation should be fairly quick once API exists on server.

**Comment by bawolf** [comment]
Will be live next push:

PUT /user/:id
```
{
   "password": "password1",
   "new_password": "password2"
}
```

If neither is included, the put will move on and look for other variables to adjust.
If one is included, but not the other, the server will send back an error.
if the the password, user_id combination is incorrect the server sill send back an error

Client is responsible for making sure the user is sure that there password is what they want it to be.
